#!/usr/bin/with-contenv bash
# shellcheck shell=bash

generate_confs() {
	umask 077
	mkdir -p /config/server
	if [ ! -f /config/server/privatekey-server ]; then
		wg genkey | tee /config/server/privatekey-server | wg pubkey >/config/server/publickey-server
	fi
	eval "$(printf %s)
  cat <<DUDE > /config/wg0.conf
$(cat /config/templates/server.conf)

DUDE"
	if [ -n "$IPV6" ] && [ "${IPV6,,}" = "true" ]; then
		sed -i 's/PostUp_IPv6/PostUp/g' /config/wg0.conf
		sed -i 's/PostDown_IPv6/PostDown/g' /config/wg0.conf
	else
		sed -i '/PostUp_IPv6/d' /config/wg0.conf
		sed -i '/PostDown_IPv6/d' /config/wg0.conf
	fi
	# Update default interface in iptable rules
	DEFAULT_INTERFACE="$(ip route | grep "default" | awk '{print $5}')"
	sed -i -e "s/eth+/${DEFAULT_INTERFACE}/g" /config/wg0.conf
	for i in "${PEERS_ARRAY[@]}"; do
		if [[ ! "${i}" =~ ^[[:alnum:]]+$ ]]; then
			echo "**** Peer ${i} contains non-alphanumeric characters and thus will be skipped. No config for peer ${i} will be generated. ****"
		else
			if [[ "${i}" =~ ^[0-9]+$ ]]; then
				PEER_ID="peer${i}"
			else
				PEER_ID="peer_${i}"
			fi
			umask 077
			mkdir -p "/config/${PEER_ID}"
			if [ ! -f "/config/${PEER_ID}/privatekey-${PEER_ID}" ]; then
				wg genkey | tee "/config/${PEER_ID}/privatekey-${PEER_ID}" | wg pubkey >"/config/${PEER_ID}/publickey-${PEER_ID}"
				wg genpsk >"/config/${PEER_ID}/presharedkey-${PEER_ID}"
			fi
			if [ -f "/config/${PEER_ID}/${PEER_ID}.conf" ]; then
				CLIENT_IPV4=$(grep "Address" "/config/${PEER_ID}/${PEER_ID}.conf" | awk '{print $NF}' | cut -d',' -f1)
				if [ -n "${ORIG_INTERFACE}" ] && [ "${INTERFACE}" != "${ORIG_INTERFACE}" ]; then
					CLIENT_IPV4="${CLIENT_IPV4//${ORIG_INTERFACE}/${INTERFACE}}"
				fi
				if [ -n "$IPV6" ] && [ "${IPV6,,}" = "true" ]; then
					CLIENT_IPV6=$(grep "Address" "/config/${PEER_ID}/${PEER_ID}.conf" | awk '{print $NF}' | cut -d',' -f2)
					if [ -n "${ORIG_INTERFACE_IPV6}" ] && [ "${INTERFACE_IPV6}" != "${ORIG_INTERFACE_IPV6}" ]; then
						CLIENT_IPV6="${CLIENT_IPV6//${ORIG_INTERFACE_IPV6}/${INTERFACE_IPV6}}"
					fi
				fi
			else
				for idx in {2..254}; do
					PROPOSED_IP="${INTERFACE}.${idx}"
					if ! grep -q -R "${PROPOSED_IP}" /config/peer*/*.conf 2>/dev/null && ([ -z "${ORIG_INTERFACE}" ] || ! grep -q -R "${ORIG_INTERFACE}.${idx}" /config/peer*/*.conf 2>/dev/null); then
						CLIENT_IPV4="${PROPOSED_IP}"
						break
					elif [[ $idx -eq 254 ]]; then
						echo "**** No free IPv4 found ****"
						exit 1
					fi
				done
				if [ -n "$IPV6" ] && [ "${IPV6,,}" = "true" ]; then
					for idx in {2..65535}; do
						n=$(printf "%x\n" "$idx")
						PROPOSED_IPV6="${INTERFACE_IPV6}::$n"
						if ! grep -q -R "${PROPOSED_IPV6}" /config/peer*/*.conf 2>/dev/null && ([ -z "${ORIG_INTERFACE_IPV6}" ] || ! grep -q -R "${ORIG_INTERFACE_IPV6}::$n" /config/peer*/*.conf 2>/dev/null); then
							CLIENT_IPV6="${PROPOSED_IPV6}"
							break
						elif [[ $idx -eq 65535 ]]; then
							echo "**** No free IPv6 found ****"
							exit 1
						fi
					done
				fi
			fi
			if [ -n "$IPV6" ] && [ "${IPV6,,}" = "true" ]; then
				CLIENT_IP="${CLIENT_IPV4},${CLIENT_IPV6}"
				ALLOWED_IP="${CLIENT_IPV4}/32,${CLIENT_IPV6}/128"
			else
				CLIENT_IP="${CLIENT_IPV4}"
				ALLOWED_IP="${CLIENT_IPV4}/32"
			fi
			if [ -f "/config/${PEER_ID}/presharedkey-${PEER_ID}" ]; then
				# create peer conf with presharedkey
				eval "$(printf %s)
        cat <<DUDE > /config/${PEER_ID}/${PEER_ID}.conf
$(cat /config/templates/peer.conf)
DUDE"
				# add peer info to server conf with presharedkey
				cat <<DUDE >>/config/wg0.conf
[Peer]
# ${PEER_ID}
PublicKey = $(cat "/config/${PEER_ID}/publickey-${PEER_ID}")
PresharedKey = $(cat "/config/${PEER_ID}/presharedkey-${PEER_ID}")
DUDE
			else
				echo "**** Existing keys with no preshared key found for ${PEER_ID}, creating confs without preshared key for backwards compatibility ****"
				# create peer conf without presharedkey
				eval "$(printf %s)
        cat <<DUDE > /config/${PEER_ID}/${PEER_ID}.conf
$(sed '/PresharedKey/d' "/config/templates/peer.conf")
DUDE"
				# add peer info to server conf without presharedkey
				cat <<DUDE >>/config/wg0.conf
[Peer]
# ${PEER_ID}
PublicKey = $(cat "/config/${PEER_ID}/publickey-${PEER_ID}")
DUDE
			fi
			SERVER_ALLOWEDIPS=SERVER_ALLOWEDIPS_PEER_${i}
			# add peer's allowedips to server conf
			if [ -n "${!SERVER_ALLOWEDIPS}" ]; then
				echo "Adding ${!SERVER_ALLOWEDIPS} to wg0.conf's AllowedIPs for peer ${i}"
				cat <<DUDE >>/config/wg0.conf
AllowedIPs = ${ALLOWED_IP},${!SERVER_ALLOWEDIPS}
DUDE
				# This is required for Site2Site VPN Configuration
				for ip in ${!SERVER_ALLOWEDIPS//,/ }; do
					for rule in {PostUp,PostDown}; do
						DEF_RULE="$(grep "$rule" </config/templates/peer-s2s.conf | head -n 1)"
						POST_RULE=${DEF_RULE//__HOMENET__/${ip}}
						sed -i -e "/^#$rule/i ${POST_RULE}" "/config/${PEER_ID}/${PEER_ID}.conf"
					done
				done
				for rule in {PostUp,PostDown}; do
					DEF_RULE="$(grep "$rule" </config/templates/peer-s2s.conf | head -n 2 | tail -n 1)"
					sed -i -e "/^#$rule/i ${DEF_RULE}" "/config/${PEER_ID}/${PEER_ID}.conf"
				done
			else
				cat <<DUDE >>/config/wg0.conf
AllowedIPs = ${ALLOWED_IP}
DUDE
			fi
			sed -i -e "/#PostUp/d" "/config/${PEER_ID}/${PEER_ID}.conf"
			sed -i -e "/#PostDown/d" "/config/${PEER_ID}/${PEER_ID}.conf"
			# add PersistentKeepalive if the peer is specified
			if [[ -n "${PERSISTENTKEEPALIVE_PEERS_ARRAY}" ]] && ([[ "${PERSISTENTKEEPALIVE_PEERS_ARRAY[0]}" = "all" ]] || printf '%s\0' "${PERSISTENTKEEPALIVE_PEERS_ARRAY[@]}" | grep -Fxqz -- "${i}"); then
				cat <<DUDE >>/config/wg0.conf
PersistentKeepalive = 25

DUDE
				cat <<DUDE >>/config/${PEER_ID}/${PEER_ID}.conf
PersistentKeepalive = 25
DUDE
			else
				cat <<DUDE >>/config/wg0.conf

DUDE
			fi
			if [ -z "${LOG_CONFS}" ] || [ "${LOG_CONFS}" = "true" ]; then
				echo "PEER ${i} QR code:"
				qrencode -t ansiutf8 <"/config/${PEER_ID}/${PEER_ID}.conf"
			else
				echo "PEER ${i} conf and QR code png saved in /config/${PEER_ID}"
			fi
			qrencode -o "/config/${PEER_ID}/${PEER_ID}.png" <"/config/${PEER_ID}/${PEER_ID}.conf"
		fi
	done
}

save_vars() {
	cat <<DUDE >/config/.donoteditthisfile
ORIG_SERVERURL="$SERVERURL"
ORIG_SERVERPORT="$SERVERPORT"
ORIG_PEERDNS="$PEERDNS"
ORIG_PEERS="$PEERS"
ORIG_INTERFACE="$INTERFACE"
ORIG_INTERFACE_IPV6="$INTERFACE_IPV6"
ORIG_ALLOWEDIPS="$ALLOWEDIPS"
ORIG_PERSISTENTKEEPALIVE_PEERS="$PERSISTENTKEEPALIVE_PEERS"
DUDE
}

#Start init
mkdir -p /config/{templates,coredns}

echo "Uname info: $(uname -a)"
# check for wireguard module
ip link del dev test 2>/dev/null
if ip link add dev test type wireguard; then
	echo "**** Wireguard module is active ****"
	ip link del dev test
	# prepare symlinks
	rm -rf /etc/wireguard
	mkdir -p /etc/wireguard
	ln -s /config/wg0.conf /etc/wireguard/wg0.conf
	# prepare templates
	cp /defaults/server.conf /config/templates/server.conf
	cp /defaults/peer.conf /config/templates/peer.conf
	cp /defaults/peer-s2s.conf /config/templates/peer-s2s.conf
	# add preshared key to user templates (backwards compatibility)
	if ! grep -q 'PresharedKey' /config/templates/peer.conf; then
		sed -i 's|^Endpoint|PresharedKey = \$\(cat /config/\${PEER_ID}/presharedkey-\${PEER_ID}\)\nEndpoint|' /config/templates/peer.conf
	fi

	if [ -n "$PEERS" ]; then
		echo "**** Server mode is selected ****"
		if [[ "$PEERS" =~ ^[0-9]+$ ]] && ! [[ "$PEERS" = *,* ]]; then
			mapfile -t PEERS_ARRAY < <(seq 1 "${PEERS}")
		else
			mapfile -t PEERS_ARRAY < <(echo "${PEERS}" | tr ',' '\n')
		fi
		if [[ -n "${PERSISTENTKEEPALIVE_PEERS}" ]]; then
			echo "**** PersistentKeepalive will be set for: ${PERSISTENTKEEPALIVE_PEERS/,/ } ****"
			mapfile -t PERSISTENTKEEPALIVE_PEERS_ARRAY < <(echo "${PERSISTENTKEEPALIVE_PEERS}" | tr ',' '\n')
		fi
		if [ -z "$SERVERURL" ] || [ "$SERVERURL" = "auto" ]; then
			SERVERURL=$(curl -s icanhazip.com)
			echo "**** SERVERURL var is either not set or is set to \"auto\", setting external IP to auto detected value of $SERVERURL ****"
		else
			echo "**** External server address is set to $SERVERURL ****"
		fi
		SERVERPORT=${SERVERPORT:-51820}
		echo "**** External server port is set to ${SERVERPORT}. Make sure that port is properly forwarded to port 51820 inside this container ****"
		INTERNAL_SUBNET=${INTERNAL_SUBNET:-172.32.1.0}
		echo "**** Internal subnet is set to $INTERNAL_SUBNET ****"
		INTERFACE=$(echo "$INTERNAL_SUBNET" | awk 'BEGIN{FS=OFS="."} NF--')
		INTERNAL_SUBNET_IPV6=${INTERNAL_SUBNET_IPV6:-2401::0}
		echo "**** Internal subnet IPv6 is set to $INTERNAL_SUBNET_IPV6 ****"
		INTERFACE_IPV6=$(echo "$INTERNAL_SUBNET_IPV6" | awk 'BEGIN{FS=OFS="::"} NF--')
		if [ -n "$IPV6" ] && [ "${IPV6,,}" = "true" ]; then
			SERVER_IP="${INTERFACE}.1,${INTERFACE_IPV6}::1"
		else
			SERVER_IP="${INTERFACE}.1"
		fi
		ALLOWEDIPS=${ALLOWEDIPS:-0.0.0.0/0, ::/0}
		echo "**** AllowedIPs for peers $ALLOWEDIPS ****"
		if [ -z "$PEERDNS" ] || [ "$PEERDNS" = "auto" ]; then
			PEERDNS="${SERVER_IP}"
			echo "**** PEERDNS var is either not set or is set to \"auto\", setting peer DNS to ${SERVER_IP} to use wireguard docker host's DNS. ****"
		else
			echo "**** Peer DNS servers will be set to $PEERDNS ****"
		fi
		if [ ! -f /config/wg0.conf ]; then
			echo "**** No wg0.conf found (maybe an initial install), generating 1 server and ${PEERS} peer/client confs ****"
			generate_confs
			save_vars
		else
			echo "**** Server mode is selected ****"
			[[ -f /config/.donoteditthisfile ]] &&
				. /config/.donoteditthisfile
			if [ "$SERVERURL" != "$ORIG_SERVERURL" ] || [ "$SERVERPORT" != "$ORIG_SERVERPORT" ] || [ "$PEERDNS" != "$ORIG_PEERDNS" ] || [ "$PEERS" != "$ORIG_PEERS" ] || [ "$INTERFACE" != "$ORIG_INTERFACE" ] || [ "$ALLOWEDIPS" != "$ORIG_ALLOWEDIPS" ] || [[ "$PERSISTENTKEEPALIVE_PEERS" != "$ORIG_PERSISTENTKEEPALIVE_PEERS" ]] || [ "$INTERFACE_IPV6" != "$ORIG_INTERFACE_IPV6" ]; then
				echo "**** Server related environment variables changed, regenerating 1 server and ${PEERS} peer/client confs ****"
				generate_confs
				save_vars
			else
				# Update default interface in iptable rules
				DEFAULT_INTERFACE="$(ip route | grep "default" | awk '{print $5}')"
				DEF_POST_UP_RULE="$(cat /config/templates/server.conf | grep PostUp)"
				DEF_POST_DOWN_RULE="$(cat /config/templates/server.conf | grep PostDown)"
				sed -i -e "s/PostUp.*/${DEF_POST_UP_RULE}/g" /config/wg0.conf
				sed -i -e "s/PostDown.*/${DEF_POST_DOWN_RULE}/g" /config/wg0.conf
				sed -i -e "s/eth+/${DEFAULT_INTERFACE}/g" /config/wg0.conf
				for i in $(find -L /config -name peer_*_postup.sh -o -name peer_*_postdown.sh);
				do
					if [[ "$i" = *postup.sh ]]; then
						DEF_RULE="$(grep "PostUp" </config/templates/peer-s2s.conf | head -n 2 | tail -n 1)"
					else
						DEF_RULE="$(grep "PostUp" </config/templates/peer-s2s.conf | head -n 2 | tail -n 1)"
					fi
					MATCH_RULE=${DEF_RULE//eth+/.*.}
					POST_RULE=${DEF_RULE//eth+/${DEFAULT_INTERFACE}}
					sed -i -e "s/${MATCH_RULE}/${POST_RULE}/g" "$i"
				done
				if [ -n "$IPV6" ] && [ "${IPV6,,}" = "true" ]; then
					IPTABLE="ip6tables"
				else
					IPTABLE="iptables"
				fi
				DEF_RULE="$IPTABLE -t nat -A POSTROUTING -o eth+ -j MASQUERADE;"
				MATCH_UP_RULE=${DEF_RULE//eth+/.*.}
				POST_UP_RULE=${DEF_RULE//eth+/${DEFAULT_INTERFACE}}
				MATCH_DOWN_RULE=${MATCH_UP_RULE//-A/-D}
				POST_DOWN_RULE=${POST_UP_RULE//-A/-D}
				sed -i "s/${MATCH_UP_RULE}/${POST_UP_RULE}/g" /config/wg0.conf
				sed -i "s/${MATCH_DOWN_RULE}/${POST_DOWN_RULE}/g" /config/wg0.conf
				echo "**** No changes to parameters. Existing configs are used. ****"
			fi
		fi
	else
		echo "**** Client mode selected. ****"
		if [ ! -f /config/wg0.conf ]; then
			echo "**** No client conf found. Provide your own client conf as \"/config/wg0.conf\" and restart the container. ****"
			sleep infinity
		else
			# Update default interface in iptable rules
			DEFAULT_INTERFACE="$(ip route | grep "default" | awk '{print $5}')"
			for rule in {PostUp,PostDown}; do
				DEF_RULE="$(grep "$rule" </config/templates/peer-s2s.conf | head -n 2 | tail -n 1)"
				MATCH_RULE=${DEF_RULE//eth+/.*.}
				POST_RULE=${DEF_RULE//eth+/${DEFAULT_INTERFACE}}
				sed -i -e "s/${MATCH_RULE}/${POST_RULE}/g" "/config/wg0.conf"
			done
		fi
		USE_COREDNS="${USE_COREDNS,,}"
		printf %s "${USE_COREDNS:-false}" >/run/s6/container_environment/USE_COREDNS
	fi

	# set up CoreDNS
	[[ ! -f /config/coredns/Corefile ]] &&
		cp /defaults/Corefile /config/coredns/Corefile

	# permissions
	chown -R xuser:xuser \
		/config
else
	echo "**** The wireguard module is not active. If you believe that your kernel should have wireguard support already, make sure that it is activated via modprobe! ****"
	exit 1
fi
