---
- name: "Create {{ xserver_name }} data directory"
  file:
    path: "{{ xserver_data }}/x-servers-data/{{ item.name }}"
    state: directory
  with_items:
    - {name: 'wireguard'}
    - {name: 'wireguard/config'}
  register: task_status
  until: task_status is successful
  retries: "{{ task_retries | int }}"
  delay: "{{ task_delay | int }}"

- name: "Archive {{ xserver_name }} files"
  archive:
    path: "{{ xserver_project_root }}/{{ xserver_name }}"
    dest: "/tmp/{{ xserver_name }}.tgz"
    format: gz
  delegate_to: 127.0.0.1
  register: task_status
  until: task_status is successful
  retries: "{{ task_retries | int }}"
  delay: "{{ task_delay | int }}"

- name: "Unarchive {{ xserver_name }} files"
  unarchive:
    src: "/tmp/{{ xserver_name }}.tgz"
    dest: "{{ xserver_root }}/x-servers/"
  register: task_status
  until: task_status is successful
  retries: "{{ task_retries | int }}"
  delay: "{{ task_delay | int }}"

- name: Fetch non-root user id
  command: id -u "{{ xserver_container_non_root_user }}"
  register: user_id
  until: user_id is successful
  retries: "{{ task_retries | int }}"
  delay: "{{ task_delay | int }}"

- name: Fetch non-root group id
  command: id -g "{{ xserver_container_non_root_group }}"
  register: group_id
  until: group_id is successful
  retries: "{{ task_retries | int }}"
  delay: "{{ task_delay | int }}"

- name: "Copy {{ xserver_name }} start script"
  template:
    src: start.sh
    dest: "{{ xserver_root }}/x-servers/{{ xserver_name }}/"
    mode: 0744
  register: task_status
  until: task_status is successful
  retries: "{{ task_retries | int }}"
  delay: "{{ task_delay | int }}"
