PostUp = DROUTE=$(ip route | grep default | awk '{print $3}'); HOMENET=__HOMENET__; ip route add $HOMENET via $DROUTE;
PostUp = iptables -t nat -A POSTROUTING -o eth+ -j MASQUERADE;
PostDown = DROUTE=$(ip route | grep default | awk '{print $3}'); HOMENET=__HOMENET__; ip route del $HOMENET via $DROUTE;
PostDown = iptables -t nat -D POSTROUTING -o eth+ -j MASQUERADE;
