FROM localhost/xs-baseimage-ubuntu:22.04

ARG ARCH="amd64"
ARG NAVIDROME_VERSION

RUN \
  echo "**** install dependencies ****" && \
  apt-get update && \
  apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    ffmpeg \
    mpv \
    sqlite \
    locales \
    net-tools \
    netcat \
    tzdata && \
  echo "**** generate locale ****" && \
  locale-gen en_US.UTF-8 && \
  echo "**** install Navidrome ****" && \
  curl -o /tmp/navidrome.tar.gz -L \
    "https://github.com/navidrome/navidrome/releases/download/v${NAVIDROME_VERSION}/navidrome_${NAVIDROME_VERSION}_linux_${ARCH}.tar.gz" && \
  tar xf /tmp/navidrome.tar.gz -C /app && \
  echo "**** clean up ****" && \
  apt-get autoremove && \
  apt-get clean && \
  rm -rf \
    /tmp/* \
    /var/lib/apt/lists/* \
    /var/tmp/* \
    /var/log/*

# add local files
COPY root/ /

# ports and volumes
EXPOSE 4533/tcp
