#!/usr/bin/with-contenv bash
#shellcheck shell=bash

exec \
    s6-notifyoncheck -d -n 300 -w 1000 -c "nc -zu localhost 5353" \
    s6-setuidgid xuser "${XS_APP}"/AdGuardHome/AdGuardHome --no-check-update -c "${XS_CONFIG}"/AdGuardHome.yaml -w "${XS_CONFIG}"