---
- name: Setup openvpn-as directories & files
  include_role:
    name: common
    tasks_from: xserver_init
  vars:
    xserver_name: "openvpn-as"

- name: Check openvpn-as root/rootless mode
  set_fact:
    ov_rootless: true
  when: xserver_rootless|bool or ov_rootless|bool

- name: Check openvpn-as force update
  set_fact:
    ov_force_update: true
  when: xserver_force_update|bool or ov_force_update|bool

- name: Setup openvpn-as root container
  include_role:
    name: common
    tasks_from: root_containers
  vars:
    xserver_name: "openvpn-as"
    xserver_image: "{{ xserver_openvpnas }}"
    xs_rootless: "{{ ov_rootless }}"
    xs_force_update: "{{ ov_force_update }}"
  when: not ov_rootless|bool

- name: Setup openvpn-as rootless container
  include_role:
    name: common
    tasks_from: rootless_containers
  vars:
    xserver_name: "openvpn-as"
    xserver_image: "{{ xserver_openvpnas }}"
    xs_rootless: "{{ ov_rootless }}"
    xs_force_update: "{{ ov_force_update }}"
  when: ov_rootless|bool
