---
- name: Setup wireguard directories & files
  include_role:
    name: common
    tasks_from: xserver_init
  vars:
    xserver_name: "wireguard"

- name: Check wireguard root/rootless mode
  set_fact:
    wg_rootless: true
  when: xserver_rootless|bool or wg_rootless|bool

- name: Check wireguard force update
  set_fact:
    wg_force_update: true
  when: xserver_force_update|bool or wg_force_update|bool

- name: Setup wireguard root container
  include_role:
    name: common
    tasks_from: root_containers
  vars:
    xserver_name: "wireguard"
    xserver_image: "{{ xserver_wireguard }}"
    xs_rootless: "{{ wg_rootless }}"
    xs_force_update: "{{ wg_force_update }}"
  when: not wg_rootless|bool

- name: Setup wireguard rootless container
  include_role:
    name: common
    tasks_from: rootless_containers
  vars:
    xserver_name: "wireguard"
    xserver_image: "{{ xserver_wireguard }}"
    xs_rootless: "{{ wg_rootless }}"
    xs_force_update: "{{ wg_force_update }}"
  when: wg_rootless|bool
