#!/usr/bin/with-contenv bash
# shellcheck shell=bash

PUID=${PUID:-911}
PGID=${PGID:-911}

groupmod -o -g "$PGID" xuser
usermod -o -u "$PUID" xuser

echo "
-------------------------------------
GID/UID
-------------------------------------
User uid:    $(id -u xuser)
User gid:    $(id -g xuser)
-------------------------------------
"
chown xuser:xuser /config
