ARG TAILSCALE_VERSION

FROM ghcr.io/tailscale/tailscale:v${TAILSCALE_VERSION} as tailscale

FROM localhost/xs-baseimage-ubuntu:22.04

ARG ARCH="amd64"

RUN \
  echo "**** install dependencies ****" && \
  apt-get update && \
  apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    iproute2 \
    iptables \
    iputils-ping \
    locales \
    net-tools \
    netcat \
    tzdata && \
  echo "**** generate locale ****" && \
  locale-gen en_US.UTF-8 && \
  echo "**** clean up ****" && \
  apt-get autoremove && \
  apt-get clean && \
  rm -rf \
    /tmp/* \
    /var/lib/apt/lists/* \
    /var/tmp/* \
    /var/log/*

# Install tailscale from upstream container image
COPY --from=tailscale /usr/local/bin/* /app/
ENV PATH=/app:${PATH}

# Set state directory to /config
ENV TS_STATE_DIR="${XS_CONFIG}"

# add local files
COPY root/ /
