FROM localhost/xs-baseimage-ubuntu:22.04

ARG ARCH="amd64"
ARG ADGUARDHOME_VERSION

RUN \
  echo "**** install dependencies ****" && \
  apt-get update && \
  apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    locales \
    net-tools \
    netcat \
    tzdata && \
  echo "**** generate locale ****" && \
  locale-gen en_US.UTF-8 && \
  echo "**** install AdguardHome ****" && \
  curl -o \
    /tmp/adguardhome.tar.gz -L \
    "https://github.com/AdguardTeam/AdGuardHome/releases/download/v${ADGUARDHOME_VERSION}/AdGuardHome_linux_${ARCH}.tar.gz" && \
  tar xf \
    /tmp/adguardhome.tar.gz -C \
    /app && \
  echo "**** clean up ****" && \
  apt-get autoremove && \
  apt-get clean && \
  rm -rf \
    /tmp/* \
    /var/lib/apt/lists/* \
    /var/tmp/* \
    /var/log/*

# add local files
COPY /root /

# ports and volumes
EXPOSE 5353/udp 3000/tcp 8080/tcp
