---
- name: Archive server files
  archive:
    path: "{{ xserver_project_root }}/cronjobs"
    dest: /tmp/cronjobs.tgz
    format: gz
  delegate_to: 127.0.0.1
  register: task_status
  until: task_status is successful
  retries: "{{ task_retries | int }}"
  delay: "{{ task_delay | int }}"

- name: Unarchive server files
  unarchive:
    src: /tmp/cronjobs.tgz
    dest: "{{ xserver_root }}/x-servers/"
  register: task_status
  until: task_status is successful
  retries: "{{ task_retries | int }}"
  delay: "{{ task_delay | int }}"

# Rootful Mode runs every Sunday 00:00
- name: Root cronjob parameters
  set_fact:
    xs_cron_schedule: "0 0 * * 0"
    xs_cron_user: "root"

- name: Copy cronjob script
  template:
    src: xs-cronjob.j2
    dest: "/etc/cron.d/xs-root"
    mode: 0644
  become: true
  register: task_status
  until: task_status is successful
  retries: "{{ task_retries | int }}"
  delay: "{{ task_delay | int }}"

- name: Fetch non-root user name
  command: id -un
  register: user_id
  until: user_id is successful
  retries: "{{ task_retries | int }}"
  delay: "{{ task_delay | int }}"

# Rootless Mode runs every Sunday 00:30
- name: Rootless cronjob parameters
  set_fact:
    xs_cron_schedule: "30 0 * * 0"
    xs_cron_user: "{{ user_id.stdout }}"

- name: Copy cronjob script
  template:
    src: xs-cronjob.j2
    dest: "/etc/cron.d/xs-rootless"
    mode: 0644
  become: true
  register: task_status
  until: task_status is successful
  retries: "{{ task_retries | int }}"
  delay: "{{ task_delay | int }}"
