---
- name: Archive server files
  archive:
    path: /x-servers/cronjobs
    dest: /tmp/cronjobs.tgz
    format: gz
  delegate_to: 127.0.0.1
  register: task_status
  until: task_status is successful
  retries: "{{ task_retries | int }}"
  delay: "{{ task_delay | int }}"

- name: Unarchive server files
  unarchive:
    src: /tmp/cronjobs.tgz
    dest: "{{ xserver_root }}/x-servers/"
  register: task_status
  until: task_status is successful
  retries: "{{ task_retries | int }}"
  delay: "{{ task_delay | int }}"

- name: Copy cronjob script
  template:
    src: xs-cronjob
    dest: "/etc/cron.d/"
    mode: 0644
  register: task_status
  until: task_status is successful
  retries: "{{ task_retries | int }}"
  delay: "{{ task_delay | int }}"
