---
- hosts: all
  pre_tasks:
  - set_fact:
      bs_force_update: false
      xs_host_update: true
      xs_root_container: false
      xs_rootless_container: false
  vars_files:
    - var_xservers.yml
  roles:
    - role: init
    # Run this role as privileged user
    - role: setup-instance
      become: true
      when: xs_host_update|bool
    - role: setup-baseimage
      when: xserver_install != "none"
    - role: setup-openvpnas
      when: xserver_install == "all" or "openvpn-as" in xserver_install
    - role: setup-wireguard
      when: xserver_install == "all" or "wireguard" in xserver_install
    - role: setup-cronjob
      when: xserver_install != "none"
    - cleanup
