---
- name: Clear podman image cache
  shell: "(sudo podman system prune -a -f)"
  register: task_status
  until: task_status is successful
  retries: "{{ task_retries | int }}"
  delay: "{{ task_delay | int }}"
